### ISSUE TITLE
Integration Testing with Docker Infrastructure

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/parcl#10]
## Summary
Implement comprehensive integration testing infrastructure using Docker to validate Parcl's functionality in realistic environments. This ensures the system works correctly with actual Git repositories, Claude CLI, and terminal emulators in isolated, reproducible environments.

## Testing Strategy and Approach
- **Containerized Testing**: Use Docker to create isolated, reproducible test environments
- **Multi-Service Testing**: Test interactions between Parcl, Git, Claude CLI, and terminal emulators
- **Environment Simulation**: Test different OS environments, Git configurations, and CLI tool versions
- **Real-World Scenarios**: Test complete workflows from initialization to cleanup

## Coverage Requirements
**Integration Test Scope:**
- Complete CLI workflow testing (init → run → status → clean)
- Git worktree operations in real repositories
- Claude CLI integration with various response scenarios
- Terminal emulator integration across different platforms
- Configuration loading and environment variable handling
- File system operations and permissions
- Concurrent execution scenarios

**Test Environments:**
- Ubuntu 22.04 LTS (primary)
- Alpine Linux (lightweight testing)
- Different Git versions (2.30+)
- Various terminal emulators (ghostty, gnome-terminal, kitty)

## Test Data and Fixtures
**Docker Test Environment Setup:**
```dockerfile
# tests/docker/Dockerfile.test
FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    ca-certificates \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Claude CLI (mock version for testing)
COPY tests/docker/mock-claude /usr/local/bin/claude
RUN chmod +x /usr/local/bin/claude

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Set up test workspace
WORKDIR /workspace
COPY . .

# Build Parcl
RUN cargo build --release

# Set up test repositories
RUN ./tests/docker/setup-test-repos.sh
```

**Docker Compose Configuration:**
```yaml
# tests/docker/docker-compose.yml
version: '3.8'

services:
  parcl-test:
    build:
      context: ../..
      dockerfile: tests/docker/Dockerfile.test
    volumes:
      - ../../:/workspace
      - test-data:/test-data
    environment:
      - RUST_LOG=debug
      - PARCL_TEST_MODE=1
    command: cargo test --test integration_tests

  git-server:
    image: gitea/gitea:latest
    ports:
      - "3000:3000"
      - "22:22"
    volumes:
      - git-data:/data
    environment:
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__security__INSTALL_LOCK=true

  claude-mock-server:
    build:
      context: tests/docker/claude-mock
    ports:
      - "8080:8080"
    environment:
      - MOCK_RESPONSE_DELAY=100ms
      - MOCK_FAILURE_RATE=0.05

volumes:
  test-data:
  git-data:
```

**Test Repository Fixtures:**
```bash
#\!/bin/bash
# tests/docker/setup-test-repos.sh

# Create test repositories with different characteristics
create_simple_repo() {
    mkdir -p /test-data/simple-repo
    cd /test-data/simple-repo
    git init
    echo "# Simple Test Repo" > README.md
    git add .
    git commit -m "Initial commit"
}

create_complex_repo() {
    mkdir -p /test-data/complex-repo
    cd /test-data/complex-repo
    git init
    
    # Create multiple branches with different files
    for branch in feature-a feature-b hotfix-1; do
        git checkout -b $branch 2>/dev/null || git checkout $branch
        echo "Content for $branch" > ${branch}.txt
        git add .
        git commit -m "Add $branch"
    done
    
    git checkout main
}

create_bare_repo() {
    git clone --bare /test-data/complex-repo /test-data/bare-repo
}
```

## Performance Benchmarks
**Integration Test Performance Targets:**
- Docker container startup: < 30 seconds
- Individual integration test: < 2 minutes
- Full integration test suite: < 15 minutes
- Git operations: < 5 seconds each
- Claude CLI simulation: < 10 seconds per request

**Resource Usage Targets:**
- Container memory usage: < 512MB per container
- Disk space usage: < 2GB for all test artifacts
- Network bandwidth: Minimal (local testing only)

## Integration with Existing Tools
**CI/CD Pipeline Integration:**
```yaml
# .github/workflows/integration-tests.yml
name: Integration Tests

on: [push, pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Run integration tests
      run: |
        cd tests/docker
        docker-compose up --build --abort-on-container-exit
        docker-compose down
    
    - name: Collect test results
      if: always()
      run: |
        docker-compose logs parcl-test > integration-test-logs.txt
    
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: integration-test-results
        path: |
          integration-test-logs.txt
          tests/docker/test-results/
```

**Makefile Integration:**
```makefile
# Integration with existing Makefile targets
test-docker-integration:
	@echo "Running Docker integration tests..."
	@cd tests/docker && docker-compose build
	@cd tests/docker && docker-compose up --abort-on-container-exit
	@cd tests/docker && docker-compose down

test-docker-debug:
	@echo "Running Docker tests in debug mode..."
	@cd tests/docker && docker-compose run --rm parcl-test bash

test-docker-logs:
	@echo "Showing Docker test logs..."
	@cd tests/docker && docker-compose logs -f parcl-test
```

## Mock Implementations for External Dependencies
**Claude CLI Mock Server:**
```rust
// tests/docker/claude-mock/src/main.rs
use std::collections::HashMap;
use warp::{Filter, Reply};

#[derive(serde::Deserialize)]
struct ClaudeRequest {
    prompt: String,
    model: Option<String>,
    session_id: Option<String>,
}

#[derive(serde::Serialize)]
struct ClaudeResponse {
    type_: String,
    subtype: String,
    result: String,
    session_id: String,
    cost_usd: f64,
    duration_ms: u64,
}

async fn handle_claude_request(req: ClaudeRequest) -> Result<impl Reply, warp::Rejection> {
    // Simulate processing delay
    tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    
    let response = ClaudeResponse {
        type_: "result".to_string(),
        subtype: "success".to_string(),
        result: generate_mock_response(&req.prompt),
        session_id: req.session_id.unwrap_or_else(|| uuid::Uuid::new_v4().to_string()),
        cost_usd: 0.001,
        duration_ms: 150,
    };
    
    Ok(warp::reply::json(&response))
}
```

**Git Server Configuration:**
```bash
# tests/docker/setup-git-server.sh
#\!/bin/bash

# Configure Git server with test repositories
setup_gitea_repos() {
    # Wait for Gitea to be ready
    until curl -s http://localhost:3000 > /dev/null; do
        sleep 1
    done
    
    # Create test repositories via API
    create_test_repo "simple-project"
    create_test_repo "complex-project"
    create_test_repo "multi-branch-project"
}

create_test_repo() {
    local repo_name=$1
    curl -X POST http://localhost:3000/api/v1/user/repos \
        -H "Content-Type: application/json" \
        -d "{\"name\": \"$repo_name\", \"private\": false}"
}
```

## Test Scenarios and Cases
**Core Workflow Testing:**
```rust
// tests/integration/workflow_tests.rs
#[tokio::test]
async fn test_complete_parcl_workflow() {
    let test_env = DockerTestEnvironment::new().await;
    
    // Test init command
    let init_result = test_env.run_parcl(&["init"]).await;
    assert\!(init_result.success);
    
    // Test run command
    let run_result = test_env.run_parcl(&["run", "-f", "test-prompt.txt"]).await;
    assert\!(run_result.success);
    
    // Test status command
    let status_result = test_env.run_parcl(&["status", "--all"]).await;
    assert\!(status_result.success);
    
    // Test clean command
    let clean_result = test_env.run_parcl(&["clean", "--all"]).await;
    assert\!(clean_result.success);
}

#[tokio::test]
async fn test_concurrent_claude_execution() {
    let test_env = DockerTestEnvironment::new().await;
    
    // Set up multiple worktrees
    test_env.setup_multi_branch_repo().await;
    
    // Run parcl with multiple concurrent jobs
    let result = test_env.run_parcl(&[
        "run", 
        "-f", "test-prompt.txt",
        "--parallel", "3"
    ]).await;
    
    assert\!(result.success);
    assert_eq\!(result.worktree_results.len(), 3);
}
```

**Error Handling Testing:**
```rust
#[tokio::test]
async fn test_git_failure_handling() {
    let test_env = DockerTestEnvironment::new().await;
    
    // Simulate Git failure
    test_env.mock_git_server.set_failure_mode(true).await;
    
    let result = test_env.run_parcl(&["run", "-f", "test-prompt.txt"]).await;
    
    assert\!(\!result.success);
    assert\!(result.error_message.contains("Git operation failed"));
}

#[tokio::test]
async fn test_claude_timeout_handling() {
    let test_env = DockerTestEnvironment::new().await;
    
    // Configure Claude mock to timeout
    test_env.claude_mock_server.set_timeout(Duration::from_secs(30)).await;
    
    let result = test_env.run_parcl(&[
        "run", 
        "-f", "test-prompt.txt",
        "--timeout", "5"
    ]).await;
    
    assert\!(\!result.success);
    assert\!(result.error_message.contains("timeout"));
}
```

## Automation Requirements
**Test Execution Pipeline:**
- Automated Docker image building and caching
- Parallel test execution across multiple containers
- Automatic cleanup of test resources
- Integration with existing CI/CD workflows

**Test Data Management:**
- Automated test fixture generation
- Test data versioning and consistency
- Cleanup of test artifacts after execution
- Secure handling of test credentials

**Monitoring and Reporting:**
- Test execution time tracking
- Resource usage monitoring
- Failure analysis and reporting
- Integration test coverage metrics

## Implementation Tasks
- [ ] Set up Docker test infrastructure
- [ ] Create mock Claude CLI server
- [ ] Set up Git server for testing
- [ ] Implement Docker test environment utilities
- [ ] Write core workflow integration tests
- [ ] Write error handling integration tests
- [ ] Write performance integration tests
- [ ] Set up CI/CD integration
- [ ] Create test data management system
- [ ] Document integration testing procedures

## Success Criteria
- ✅ Complete workflow testing in isolated environments
- ✅ All integration tests pass consistently
- ✅ Mock services behave realistically
- ✅ Performance targets met
- ✅ CI/CD integration working smoothly
- ✅ Clear documentation for adding new integration tests

## Dependencies
- Docker and Docker Compose
- Mock Claude CLI implementation
- Git server (Gitea or similar)
- CI/CD platform integration
- Test data management tools

**Priority:** High
**Estimated Effort:** 3-4 weeks
**Labels:** testing, integration, docker, infrastructure
