### ISSUE TITLE
Configuration System for Evaluation Parameters

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/parcl#15]
## Overview
Implement comprehensive configuration management for the evaluation system, supporting hierarchical configuration loading, parameter validation, and runtime customization.

## Configuration Hierarchy
Support configuration loading in order of precedence:
1. `.parcl/config.yaml` (project-level)
2. `~/.config/parcl/config.yaml` (user-level)
3. `/etc/parcl/config.yaml` (system-level)
4. Environment variable overrides
5. Command-line flag overrides

## Evaluation Configuration Schema
```yaml
evaluation:
  enabled: false                    # Enable/disable evaluation
  script: scripts/eval.sh          # Path to evaluation script
  script_args:                     # Arguments to pass to script
    - ${worktree}                  # Variable substitution
    - ${model}
    - ${session_id}
  script_timeout: 300              # Timeout in seconds
  working_directory: .             # Working directory for script
  environment:                     # Additional environment variables
    EVAL_MODE: "strict"
    LOG_LEVEL: "info"
  parallel_limit: 5                # Max concurrent evaluations
  retry_count: 3                   # Retry failed evaluations
  retry_delay: 5                   # Delay between retries (seconds)
  output_format: json              # Output format (json, yaml, text)
  results_dir: .parcl/results      # Directory for evaluation results
  preserve_outputs: true           # Keep evaluation outputs
  fail_fast: false                 # Stop on first failure
```

## Variable Substitution System
Support dynamic variable replacement in configuration:
- `${worktree}` - Current worktree path
- `${model}` - Claude model being used
- `${session_id}` - Claude session identifier
- `${timestamp}` - Execution timestamp
- `${branch}` - Git branch name
- `${commit}` - Git commit hash
- `${PROJECT_NAME}` - Environment variable expansion

## Configuration Validation
- **Schema Validation**: Ensure all required fields are present
- **Type Checking**: Validate data types and formats
- **Range Validation**: Check numeric values are within acceptable ranges
- **Path Validation**: Verify script paths exist and are executable
- **Permission Checks**: Ensure directories are writable
- **Dependency Validation**: Verify required tools are available

## Runtime Configuration
- **Hot Reload**: Support configuration changes without restart
- **Profile Support**: Multiple evaluation profiles (dev, test, prod)
- **Conditional Configuration**: Environment-based configuration
- **Override Mechanism**: Command-line parameter overrides

## Integration with Viper
- Leverage existing Viper configuration system
- Support automatic environment variable binding
- Implement configuration watching for changes
- Provide configuration debugging and inspection

## Error Handling
- **Missing Configuration**: Graceful fallbacks to defaults
- **Invalid Values**: Clear error messages with suggestions
- **Permission Issues**: Helpful guidance for resolution
- **Validation Failures**: Detailed error reporting

## Testing Requirements
- Unit tests for configuration parsing
- Validation testing with invalid configurations
- Integration tests with different configuration sources
- Environment variable override testing

## Acceptance Criteria
- [ ] Hierarchical configuration loading works correctly
- [ ] Variable substitution functions properly
- [ ] Configuration validation catches all error cases
- [ ] Environment variable overrides work
- [ ] Command-line parameter overrides work
- [ ] Configuration hot reload functions
- [ ] Integration with existing Viper system complete
- [ ] Comprehensive test coverage achieved

🤖 Generated with [Claude Code](https://claude.ai/code)
