### ISSUE TITLE
Implement `parcl init` command

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/parcl#2]
## Description
Implement the `parcl init` command to initialize project configuration for Parcl. This command should create the necessary configuration files and directory structure to get a new Parcl project up and running.

## Functionality
The `parcl init` command should:
- Create `.parcl/` directory in the current working directory
- Generate default configuration file (`.parcl/config.yaml`) with sensible defaults
- Set up basic project structure for worktrees and evaluation
- Validate that the current directory is a Git repository
- Handle existing configurations gracefully (prompt for overwrite or merge)

## Acceptance Criteria
- [ ] Command creates `.parcl/config.yaml` with default configuration values
- [ ] Command creates necessary directory structure (`.parcl/worktrees/`, `.parcl/eval/`, etc.)
- [ ] Command validates current directory is a Git repository
- [ ] Command handles existing `.parcl/` directory gracefully
- [ ] Command provides clear success/failure feedback to user
- [ ] Command supports `--force` flag to overwrite existing configuration
- [ ] Command supports `--dry-run` flag to preview changes without making them
- [ ] Configuration includes all required sections: git, claude, prompt, runner, evaluation

### Configuration Structure
The generated config should include:
```yaml
git:
  default_branch: main
  worktree_prefix: parcl-
  bare_repo_path: .parcl/repo
  worktree_base_path: .parcl/worktrees
  auto_cleanup: true

claude:
  api_key: "${ANTHROPIC_API_KEY}"
  model: claude-3-5-sonnet-20241022
  max_requests: 5
  concurrency: 5
  temperature: 0
  timeout: 300

prompt:
  default_file: prompt.txt
  templates_dir: .parcl/templates
  variables:
    project_name: "${PROJECT_NAME}"

runner:
  parallel_limit: 5
  output_format: json
  progress_display: spinner
  continue_on_error: false
  capture_output: true

evaluation:
  enabled: false
  scripts_dir: .parcl/eval
  output_dir: .parcl/results
```

### Directory Structure
```
.parcl/
├── config.yaml
├── worktrees/
├── templates/
├── eval/
└── results/
```

### CLI Interface
```bash
parcl init [flags]

Flags:
  --force        Overwrite existing configuration
  --dry-run      Preview changes without making them
  --help, -h     Show help information
```

### Files to Modify/Create
- `src/cli/init.rs` - Main implementation
- `src/config/mod.rs` - Configuration validation and defaults
- Update `src/main.rs` to register the init command

### Dependencies
- Use existing configuration system (`internal/config/`)
- Integrate with Git wrapper (`internal/wrappers/git/`) for repository validation
- Use Viper for configuration file generation

## Related Issues
- Depends on configuration system implementation
- Related to `parcl run` command for configuration usage

## Estimated Complexity
**Medium** - Involves file system operations, configuration generation, and user interaction patterns.

## Definition of Done
- [ ] Command implemented and tested
- [ ] Unit tests covering all scenarios (existing config, invalid git repo, etc.)
- [ ] Integration tests verifying generated configuration is valid
- [ ] Documentation updated
- [ ] Error handling for edge cases (permissions, disk space, etc.)
