### ISSUE TITLE
Benchmarking and Performance Testing Infrastructure

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/parcl#22]
## Summary
Establish comprehensive benchmarking and performance testing infrastructure to ensure Parcl maintains optimal performance across various workloads and scales efficiently with increased parallelism, repository sizes, and system load.

## Testing Strategy and Approach
- **Micro-benchmarks**: Test individual function and module performance
- **Integration benchmarks**: Measure end-to-end workflow performance
- **Scalability testing**: Validate performance with varying workload sizes
- **Regression detection**: Automatically detect performance regressions
- **Resource profiling**: Monitor memory, CPU, and I/O usage patterns

## Coverage Requirements
**Performance Test Categories:**
- Configuration parsing and validation speed
- Git worktree creation and management operations
- Claude CLI interaction and response handling
- Concurrent execution performance and scaling
- File system operations and cleanup efficiency
- Memory usage and allocation patterns
- Network I/O and timeout handling

**Scalability Dimensions:**
- Number of concurrent worktrees (1-50)
- Repository size and complexity (small to large)
- Prompt size and complexity (100 chars to 10KB)
- System resource constraints (limited CPU/memory)
- Network latency simulation (local to high-latency)

## Test Data and Fixtures
**Benchmark Test Data:**
```rust
// benches/test_data.rs
use std::collections::HashMap;

pub struct BenchmarkData {
    pub small_repo: TestRepo,
    pub medium_repo: TestRepo,
    pub large_repo: TestRepo,
    pub complex_repo: TestRepo,
}

pub struct TestRepo {
    pub path: PathBuf,
    pub branch_count: usize,
    pub commit_count: usize,
    pub file_count: usize,
    pub total_size_mb: usize,
}

impl BenchmarkData {
    pub fn new() -> Self {
        Self {
            small_repo: TestRepo::new_small(),
            medium_repo: TestRepo::new_medium(),
            large_repo: TestRepo::new_large(),
            complex_repo: TestRepo::new_complex(),
        }
    }
}

// Generate repositories of various sizes for testing
impl TestRepo {
    fn new_small() -> Self {
        Self {
            path: create_test_repo_with_params(5, 20, 100),
            branch_count: 5,
            commit_count: 20,
            file_count: 100,
            total_size_mb: 1,
        }
    }
    
    fn new_medium() -> Self {
        Self {
            path: create_test_repo_with_params(15, 100, 1000),
            branch_count: 15,
            commit_count: 100,
            file_count: 1000,
            total_size_mb: 50,
        }
    }
    
    fn new_large() -> Self {
        Self {
            path: create_test_repo_with_params(50, 500, 10000),
            branch_count: 50,
            commit_count: 500,
            file_count: 10000,
            total_size_mb: 500,
        }
    }
}
```

**Performance Test Prompts:**
```
# benches/fixtures/prompts/
├── simple.txt          # "List all files in the repository"
├── medium.txt          # "Analyze the codebase architecture and suggest improvements"
├── complex.txt         # "Refactor the entire module system for better performance"
├── code_generation.txt # "Generate comprehensive unit tests for all modules"
└── large_prompt.txt    # Multi-page detailed requirements (5KB+)
```

**Configuration Variations:**
```yaml
# benches/fixtures/configs/performance_test_configs.yaml
configurations:
  minimal:
    claude:
      max_requests: 1
      concurrency: 1
      timeout: 30
    runner:
      parallel_limit: 1
      
  standard:
    claude:
      max_requests: 5
      concurrency: 3
      timeout: 300
    runner:
      parallel_limit: 5
      
  high_performance:
    claude:
      max_requests: 10
      concurrency: 10
      timeout: 600
    runner:
      parallel_limit: 20
```

## Performance Benchmarks
**Micro-benchmark Targets:**
```rust
// benches/micro_benchmarks.rs
use criterion::{black_box, criterion_group, criterion_main, Criterion, BenchmarkId};

fn config_parsing_benchmark(c: &mut Criterion) {
    let mut group = c.benchmark_group("config_parsing");
    
    for config_size in [1, 10, 100].iter() {
        group.bench_with_input(
            BenchmarkId::new("yaml_parse", config_size),
            config_size,
            |b, &size| {
                let yaml = generate_config_yaml(size);
                b.iter(|| {
                    ParclConfig::from_yaml(black_box(&yaml))
                });
            },
        );
    }
    
    group.finish();
}

fn git_operations_benchmark(c: &mut Criterion) {
    let mut group = c.benchmark_group("git_operations");
    
    for repo_type in ["small", "medium", "large"].iter() {
        group.bench_with_input(
            BenchmarkId::new("worktree_create", repo_type),
            repo_type,
            |b, &repo_type| {
                let repo = get_test_repo(repo_type);
                b.iter(|| {
                    let worktree_name = format\!("bench-{}", rand::random::<u32>());
                    create_and_cleanup_worktree(black_box(&repo), &worktree_name)
                });
            },
        );
    }
    
    group.finish();
}

// Performance targets (baseline expectations)
const PERFORMANCE_TARGETS: &[(&str, u64)] = &[
    ("config_parse_small", 100),      // 100μs for small config
    ("config_parse_large", 1000),     // 1ms for large config
    ("worktree_create_small", 500),   // 500ms for small repo
    ("worktree_create_large", 2000),  // 2s for large repo
    ("claude_request_mock", 100),     // 100ms for mocked request
    ("concurrent_execution_5", 3000), // 3s for 5 concurrent operations
];
```

**Integration Benchmark Targets:**
```rust
// benches/integration_benchmarks.rs

fn end_to_end_workflow_benchmark(c: &mut Criterion) {
    let mut group = c.benchmark_group("e2e_workflow");
    
    for scenario in [
        ("simple_3_worktrees", 3),
        ("medium_10_worktrees", 10),
        ("large_25_worktrees", 25),
    ].iter() {
        group.bench_with_input(
            BenchmarkId::new("complete_workflow", scenario.0),
            &scenario.1,
            |b, &worktree_count| {
                b.iter(|| {
                    run_complete_parcl_workflow(black_box(worktree_count))
                });
            },
        );
    }
    
    group.finish();
}

fn scaling_benchmark(c: &mut Criterion) {
    let mut group = c.benchmark_group("scaling");
    group.sample_size(10); // Fewer samples for long-running tests
    
    for concurrency in [1, 2, 5, 10, 20].iter() {
        group.bench_with_input(
            BenchmarkId::new("concurrent_execution", concurrency),
            concurrency,
            |b, &concurrency| {
                b.iter(|| {
                    run_concurrent_parcl_operations(black_box(concurrency))
                });
            },
        );
    }
    
    group.finish();
}
```

**Memory Usage Benchmarks:**
```rust
// benches/memory_benchmarks.rs
use std::alloc::{GlobalAlloc, Layout, System};
use std::sync::atomic::{AtomicUsize, Ordering};

struct TrackingAllocator;

static ALLOCATED: AtomicUsize = AtomicUsize::new(0);

unsafe impl GlobalAlloc for TrackingAllocator {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        let ptr = System.alloc(layout);
        if \!ptr.is_null() {
            ALLOCATED.fetch_add(layout.size(), Ordering::SeqCst);
        }
        ptr
    }
    
    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        System.dealloc(ptr, layout);
        ALLOCATED.fetch_sub(layout.size(), Ordering::SeqCst);
    }
}

#[global_allocator]
static GLOBAL: TrackingAllocator = TrackingAllocator;

fn memory_usage_benchmark(c: &mut Criterion) {
    let mut group = c.benchmark_group("memory_usage");
    
    group.bench_function("memory_baseline", |b| {
        b.iter(|| {
            let start_memory = ALLOCATED.load(Ordering::SeqCst);
            run_parcl_operation();
            let end_memory = ALLOCATED.load(Ordering::SeqCst);
            black_box(end_memory - start_memory)
        });
    });
    
    group.finish();
}
```

## Integration with Existing Tools
**Criterion.rs Configuration:**
```toml
# Add to Cargo.toml
[[bench]]
name = "micro_benchmarks"
harness = false

[[bench]]
name = "integration_benchmarks" 
harness = false

[[bench]]
name = "memory_benchmarks"
harness = false

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
```

**CI Integration for Performance Testing:**
```yaml
# .github/workflows/performance.yml
name: Performance Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - name: Cache benchmark data
      uses: actions/cache@v3
      with:
        path: target/criterion
        key: criterion-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run benchmarks
      run: |
        cargo bench --bench micro_benchmarks
        cargo bench --bench integration_benchmarks
        
    - name: Store benchmark results
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'cargo'
        output-file-path: target/criterion/reports/index.html
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        
    - name: Performance regression check
      run: |
        # Compare with baseline and fail if regression > 20%
        ./scripts/check_performance_regression.sh
```

**Performance Monitoring Dashboard:**
```bash
#\!/bin/bash
# scripts/performance_dashboard.sh

# Generate comprehensive performance report
generate_performance_report() {
    echo "# Parcl Performance Report"
    echo "Generated: $(date)"
    echo ""
    
    # Run benchmarks and collect metrics
    cargo bench --bench micro_benchmarks -- --output-format json > micro_results.json
    cargo bench --bench integration_benchmarks -- --output-format json > integration_results.json
    
    # Generate charts and summaries
    python3 scripts/generate_performance_charts.py
    
    # Check for regressions
    python3 scripts/performance_regression_analysis.py
}
```

## Mock Implementations for External Dependencies
**Performance-Oriented Mocks:**
```rust
// benches/mocks/performance_mocks.rs

pub struct BenchmarkClaudeMock {
    response_times: Vec<Duration>,
    current_index: AtomicUsize,
}

impl BenchmarkClaudeMock {
    pub fn new_with_latencies(latencies: Vec<Duration>) -> Self {
        Self {
            response_times: latencies,
            current_index: AtomicUsize::new(0),
        }
    }
    
    pub fn new_realistic() -> Self {
        // Based on actual Claude API response times
        let latencies = vec\![
            Duration::from_millis(150),  // Fast response
            Duration::from_millis(300),  // Typical response
            Duration::from_millis(1000), // Slow response
            Duration::from_millis(2000), // Very slow response
        ];
        Self::new_with_latencies(latencies)
    }
}

impl ClaudeExecutor for BenchmarkClaudeMock {
    async fn execute(&self, request: ClaudeRequest) -> ClaudeResult {
        let index = self.current_index.fetch_add(1, Ordering::SeqCst);
        let delay = self.response_times[index % self.response_times.len()];
        
        tokio::time::sleep(delay).await;
        
        Ok(ClaudeResponse {
            result: "Benchmark response".to_string(),
            session_id: generate_session_id(),
            cost_usd: 0.001,
            duration_ms: delay.as_millis() as u64,
        })
    }
}
```

## Automation Requirements
**Automated Performance Testing:**
- Continuous benchmark execution on main branch
- Performance regression detection with alerts
- Automated baseline updates for new releases
- Integration with performance monitoring systems

**Performance Alerting:**
```bash
# scripts/performance_alerts.sh
#\!/bin/bash

check_performance_regression() {
    local threshold="20" # 20% regression threshold
    local baseline_file="performance_baseline.json"
    local current_results="current_performance.json"
    
    # Compare current results with baseline
    regression_percentage=$(python3 scripts/calculate_regression.py \
        "$baseline_file" "$current_results")
    
    if (( $(echo "$regression_percentage > $threshold" | bc -l) )); then
        echo "Performance regression detected: ${regression_percentage}%"
        # Send alert notification
        curl -X POST "$SLACK_WEBHOOK" -d "{
            \"text\": \"🚨 Performance regression detected in Parcl: ${regression_percentage}%\"
        }"
        exit 1
    fi
}
```

**Resource Usage Monitoring:**
```rust
// benches/resource_monitoring.rs
use sysinfo::{System, SystemExt, ProcessExt, PidExt};

pub struct ResourceMonitor {
    system: System,
    process_id: u32,
    start_time: Instant,
    measurements: Vec<ResourceMeasurement>,
}

#[derive(Debug, Clone)]
pub struct ResourceMeasurement {
    timestamp: Duration,
    cpu_usage_percent: f32,
    memory_usage_mb: u64,
    disk_read_mb: u64,
    disk_write_mb: u64,
}

impl ResourceMonitor {
    pub fn start_monitoring() -> Self {
        let mut system = System::new_all();
        system.refresh_all();
        
        Self {
            system,
            process_id: std::process::id(),
            start_time: Instant::now(),
            measurements: Vec::new(),
        }
    }
    
    pub fn record_measurement(&mut self) {
        self.system.refresh_all();
        
        if let Some(process) = self.system.process(Pid::from(self.process_id as usize)) {
            let measurement = ResourceMeasurement {
                timestamp: self.start_time.elapsed(),
                cpu_usage_percent: process.cpu_usage(),
                memory_usage_mb: process.memory() / 1024 / 1024,
                disk_read_mb: process.disk_usage().read_bytes / 1024 / 1024,
                disk_write_mb: process.disk_usage().written_bytes / 1024 / 1024,
            };
            
            self.measurements.push(measurement);
        }
    }
    
    pub fn generate_report(&self) -> ResourceReport {
        ResourceReport::from_measurements(&self.measurements)
    }
}
```

## Implementation Tasks
- [ ] Set up Criterion.rs benchmarking infrastructure
- [ ] Implement micro-benchmarks for core functions
- [ ] Create integration benchmarks for complete workflows
- [ ] Set up memory usage and resource monitoring
- [ ] Implement scalability testing framework
- [ ] Create performance regression detection system
- [ ] Set up CI integration for automated benchmarking
- [ ] Create performance monitoring dashboard
- [ ] Implement alerting for performance regressions
- [ ] Document performance testing procedures

## Success Criteria
- ✅ Comprehensive benchmark coverage for all critical paths
- ✅ Automated performance regression detection
- ✅ Performance targets met across all test scenarios
- ✅ Scalability validated up to target workload sizes
- ✅ Resource usage within acceptable bounds
- ✅ CI integration providing consistent performance feedback

## Dependencies
- Criterion.rs for benchmarking framework
- Sysinfo for system resource monitoring
- CI/CD integration for automated testing
- Performance monitoring and alerting systems
- Statistical analysis tools for regression detection

**Priority:** Medium-High
**Estimated Effort:** 2-3 weeks
**Labels:** testing, performance, benchmarking, scalability
