### ISSUE TITLE
End-to-End Testing Scenarios and Workflow Validation

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/parcl#24]
## Summary
Implement comprehensive end-to-end testing scenarios that validate complete Parcl workflows in realistic environments. These tests ensure the entire system works correctly from user input to final output, including all integrations and dependencies.

## Testing Strategy and Approach
- **Complete Workflow Testing**: Test entire user journeys from CLI invocation to completion
- **Real Environment Simulation**: Use actual Git repositories, Claude CLI interactions, and terminal emulators
- **User Scenario Coverage**: Cover common, edge case, and error scenarios users might encounter
- **Cross-Platform Validation**: Ensure consistent behavior across different operating systems
- **Performance Validation**: Verify acceptable performance in realistic usage scenarios

## Coverage Requirements
**Primary User Workflows:**
1. **Project Initialization**: `parcl init` → configuration setup → validation
2. **Simple Execution**: `parcl run -f prompt.txt` → worktree creation → Claude execution → cleanup
3. **Complex Execution**: Multiple branches, concurrent execution, long-running operations
4. **Status Monitoring**: `parcl status` during and after operations
5. **Cleanup Operations**: `parcl clean` with various filters and scenarios
6. **Error Recovery**: Handling failures at different stages

**Integration Points:**
- Git repository interactions (clone, worktree, branch operations)
- Claude CLI communication (requests, responses, session management)
- Terminal emulator integration (ghostty, gnome-terminal, kitty)
- File system operations (permissions, disk space, cleanup)
- Configuration management (hierarchical loading, environment variables)

## Test Data and Fixtures
**Test Repository Scenarios:**
```bash
# tests/e2e/fixtures/setup_test_repos.sh
#\!/bin/bash

setup_simple_repo() {
    local repo_dir="$1"
    cd "$repo_dir"
    
    git init
    git config user.name "E2E Test"
    git config user.email "e2e@parcl.test"
    
    echo "# Simple Project" > README.md
    echo "console.log('Hello World');" > main.js
    
    git add .
    git commit -m "Initial commit"
    
    # Create a feature branch
    git checkout -b feature/new-feature
    echo "// New feature code" >> main.js
    git add .
    git commit -m "Add new feature"
    
    git checkout main
}

setup_complex_repo() {
    local repo_dir="$1"
    cd "$repo_dir"
    
    git init
    git config user.name "E2E Test"
    git config user.email "e2e@parcl.test"
    
    # Create complex directory structure
    mkdir -p src/{components,utils,tests}
    mkdir -p docs
    mkdir -p scripts
    
    # Add various file types
    echo "# Complex Project" > README.md
    echo "rust" > src/main.rs
    echo "typescript" > src/app.ts
    echo "python" > scripts/deploy.py
    echo "markdown" > docs/api.md
    
    git add .
    git commit -m "Initial complex structure"
    
    # Create multiple feature branches
    for branch in feature/auth feature/ui feature/api hotfix/security; do
        git checkout -b "$branch"
        echo "// Changes for $branch" > "src/${branch##*/}.rs"
        git add .
        git commit -m "Implement $branch"
    done
    
    git checkout main
}

setup_large_repo() {
    local repo_dir="$1"
    cd "$repo_dir"
    
    git init
    git config user.name "E2E Test"
    git config user.email "e2e@parcl.test"
    
    # Generate large repository with many files and history
    for i in {1..100}; do
        mkdir -p "module_$i/src"
        echo "// Module $i implementation" > "module_$i/src/lib.rs"
        echo "# Module $i" > "module_$i/README.md"
        
        git add "module_$i"
        git commit -m "Add module $i"
        
        # Create branches for some modules
        if [ $((i % 10)) -eq 0 ]; then
            git checkout -b "feature/module_$i"
            echo "// Enhanced module $i" >> "module_$i/src/lib.rs"
            git add .
            git commit -m "Enhance module $i"
            git checkout main
        fi
    done
}
```

**Test Prompts and Scenarios:**
```
# tests/e2e/fixtures/prompts/
├── simple_analysis.txt     # "Analyze the codebase structure"
├── code_review.txt         # "Review the code for potential improvements"
├── test_generation.txt     # "Generate comprehensive unit tests"
├── refactoring.txt         # "Refactor for better performance"
├── documentation.txt       # "Add comprehensive documentation"
├── security_audit.txt      # "Perform a security audit"
└── migration.txt          # "Migrate to new framework version"
```

**Configuration Test Cases:**
```yaml
# tests/e2e/fixtures/configs/
# minimal_config.yaml
parcl:
  git:
    default_branch: main
  claude:
    model: claude-3-5-sonnet-20241022
    timeout: 60

# production_config.yaml  
parcl:
  git:
    default_branch: main
    worktree_prefix: parcl-
    auto_cleanup: true
  claude:
    model: claude-3-5-sonnet-20241022
    max_requests: 10
    concurrency: 5
    timeout: 300
  runner:
    parallel_limit: 10
    continue_on_error: false
    
# edge_case_config.yaml
parcl:
  git:
    default_branch: "feature/very-long-branch-name-that-tests-limits"
    worktree_prefix: "very-long-prefix-name-"
  claude:
    max_requests: 1
    concurrency: 1
    timeout: 5
```

## Test Scenarios and Cases
**Core Workflow Tests:**
```rust
// tests/e2e/workflow_tests.rs
use std::time::Duration;
use tempfile::TempDir;
use tokio::process::Command;

#[tokio::test]
async fn test_simple_workflow_success() {
    let test_env = E2ETestEnvironment::new().await;
    
    // Setup: Create simple repository
    test_env.setup_repository("simple").await;
    
    // Step 1: Initialize Parcl project
    let init_result = test_env.run_parcl(&["init"]).await;
    assert\!(init_result.success, "Init command failed: {}", init_result.stderr);
    assert\!(test_env.config_exists());
    
    // Step 2: Run Parcl with simple prompt
    let run_result = test_env.run_parcl(&[
        "run", 
        "-f", "tests/e2e/fixtures/prompts/simple_analysis.txt"
    ]).await;
    assert\!(run_result.success, "Run command failed: {}", run_result.stderr);
    
    // Verify worktrees were created
    assert\!(test_env.worktree_count() > 0);
    
    // Step 3: Check status
    let status_result = test_env.run_parcl(&["status", "--all"]).await;
    assert\!(status_result.success, "Status command failed: {}", status_result.stderr);
    assert\!(status_result.stdout.contains("completed"));
    
    // Step 4: Clean up
    let clean_result = test_env.run_parcl(&["clean", "--all"]).await;
    assert\!(clean_result.success, "Clean command failed: {}", clean_result.stderr);
    assert_eq\!(test_env.worktree_count(), 0);
}

#[tokio::test]
async fn test_concurrent_execution_workflow() {
    let test_env = E2ETestEnvironment::new().await;
    test_env.setup_repository("complex").await;
    
    // Configure for concurrent execution
    test_env.set_config("
        parcl:
          runner:
            parallel_limit: 5
          claude:
            concurrency: 3
    ").await;
    
    // Run with multiple branches
    let run_result = test_env.run_parcl(&[
        "run",
        "-f", "tests/e2e/fixtures/prompts/code_review.txt",
        "--branches", "feature/auth,feature/ui,feature/api"
    ]).await;
    
    assert\!(run_result.success);
    assert_eq\!(test_env.worktree_count(), 3);
    
    // Verify all operations completed successfully
    let status_result = test_env.run_parcl(&["status", "--all"]).await;
    assert\!(status_result.success);
    
    let completed_count = status_result.stdout
        .lines()
        .filter(|line| line.contains("completed"))
        .count();
    assert_eq\!(completed_count, 3);
}

#[tokio::test]
async fn test_error_recovery_workflow() {
    let test_env = E2ETestEnvironment::new().await;
    test_env.setup_repository("simple").await;
    
    // Simulate Claude CLI failure
    test_env.claude_mock.set_failure_rate(1.0).await;
    
    let run_result = test_env.run_parcl(&[
        "run",
        "-f", "tests/e2e/fixtures/prompts/simple_analysis.txt"
    ]).await;
    
    // Should fail gracefully
    assert\!(\!run_result.success);
    assert\!(run_result.stderr.contains("Claude execution failed"));
    
    // Verify cleanup occurred
    assert_eq\!(test_env.worktree_count(), 0);
    
    // Verify state is clean for retry
    test_env.claude_mock.set_failure_rate(0.0).await;
    let retry_result = test_env.run_parcl(&[
        "run",
        "-f", "tests/e2e/fixtures/prompts/simple_analysis.txt"
    ]).await;
    
    assert\!(retry_result.success);
}
```

**Cross-Platform Tests:**
```rust
// tests/e2e/platform_tests.rs

#[tokio::test]
#[cfg(target_os = "linux")]
async fn test_linux_terminal_integration() {
    let test_env = E2ETestEnvironment::new().await;
    test_env.setup_repository("simple").await;
    
    // Test with different Linux terminal emulators
    for terminal in ["gnome-terminal", "kitty"] {
        if test_env.terminal_available(terminal).await {
            let result = test_env.run_parcl(&[
                "run",
                "-f", "tests/e2e/fixtures/prompts/simple_analysis.txt",
                "--terminal", terminal
            ]).await;
            
            assert\!(result.success, "Failed with terminal: {}", terminal);
        }
    }
}

#[tokio::test]
#[cfg(target_os = "macos")]
async fn test_macos_terminal_integration() {
    let test_env = E2ETestEnvironment::new().await;
    test_env.setup_repository("simple").await;
    
    // Test with macOS terminals
    for terminal in ["Terminal", "iTerm"] {
        if test_env.terminal_available(terminal).await {
            let result = test_env.run_parcl(&[
                "run",
                "-f", "tests/e2e/fixtures/prompts/simple_analysis.txt",
                "--terminal", terminal
            ]).await;
            
            assert\!(result.success, "Failed with terminal: {}", terminal);
        }
    }
}
```

**Performance and Scalability Tests:**
```rust
// tests/e2e/performance_tests.rs

#[tokio::test]
async fn test_large_repository_handling() {
    let test_env = E2ETestEnvironment::new().await;
    test_env.setup_repository("large").await;
    
    let start_time = Instant::now();
    
    let result = test_env.run_parcl(&[
        "run",
        "-f", "tests/e2e/fixtures/prompts/simple_analysis.txt"
    ]).await;
    
    let duration = start_time.elapsed();
    
    assert\!(result.success);
    assert\!(duration < Duration::from_secs(300), "Operation took too long: {:?}", duration);
    
    // Verify memory usage was reasonable
    let peak_memory = test_env.get_peak_memory_usage();
    assert\!(peak_memory < 1024 * 1024 * 1024, "Memory usage too high: {} bytes", peak_memory);
}

#[tokio::test]
async fn test_high_concurrency_handling() {
    let test_env = E2ETestEnvironment::new().await;
    test_env.setup_repository("complex").await;
    
    // Configure for high concurrency
    test_env.set_config("
        parcl:
          runner:
            parallel_limit: 20
          claude:
            concurrency: 10
    ").await;
    
    let result = test_env.run_parcl(&[
        "run",
        "-f", "tests/e2e/fixtures/prompts/code_review.txt",
        "--all-branches"
    ]).await;
    
    assert\!(result.success);
    
    // Verify all branches were processed
    let branch_count = test_env.get_branch_count();
    assert_eq\!(test_env.worktree_count(), branch_count);
}
```

## Performance Benchmarks
**E2E Performance Targets:**
- Simple workflow (1 worktree): < 30 seconds
- Complex workflow (5 worktrees): < 2 minutes
- Large repository handling: < 5 minutes
- High concurrency (10+ worktrees): < 3 minutes
- Memory usage: < 1GB peak usage
- Cleanup operations: < 10 seconds

**Resource Usage Monitoring:**
```rust
// tests/e2e/resource_monitor.rs
pub struct E2EResourceMonitor {
    start_time: Instant,
    peak_memory: AtomicUsize,
    cpu_samples: Mutex<Vec<f32>>,
    disk_usage: AtomicUsize,
}

impl E2EResourceMonitor {
    pub fn start() -> Self {
        let monitor = Self {
            start_time: Instant::now(),
            peak_memory: AtomicUsize::new(0),
            cpu_samples: Mutex::new(Vec::new()),
            disk_usage: AtomicUsize::new(0),
        };
        
        // Start background monitoring
        let monitor_clone = monitor.clone();
        tokio::spawn(async move {
            monitor_clone.monitor_resources().await;
        });
        
        monitor
    }
    
    async fn monitor_resources(&self) {
        let mut interval = tokio::time::interval(Duration::from_secs(1));
        
        loop {
            interval.tick().await;
            
            let memory_usage = get_current_memory_usage();
            self.peak_memory.fetch_max(memory_usage, Ordering::Relaxed);
            
            let cpu_usage = get_current_cpu_usage();
            self.cpu_samples.lock().unwrap().push(cpu_usage);
            
            let disk_usage = get_current_disk_usage();
            self.disk_usage.store(disk_usage, Ordering::Relaxed);
        }
    }
}
```

## Integration with Existing Tools
**Test Infrastructure Integration:**
```toml
# Cargo.toml additions for E2E testing
[[test]]
name = "e2e_tests"
path = "tests/e2e/mod.rs"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
tempfile = "3.0"
assert_cmd = "2.0"
predicates = "3.0"
serde_json = "1.0"
sysinfo = "0.30"
```

**CI Integration:**
```yaml
# .github/workflows/e2e-tests.yml
name: End-to-End Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up test environment
      run: |
        # Install Claude CLI mock
        ./tests/e2e/setup/install_claude_mock.sh
        
        # Install terminal emulators
        sudo apt-get update
        sudo apt-get install -y gnome-terminal
        
    - name: Run E2E tests
      run: |
        cargo test --test e2e_tests -- --test-threads=1
        
    - name: Collect test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: e2e-test-results-linux
        path: |
          tests/e2e/results/
          tests/e2e/logs/
          
  e2e-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up test environment
      run: |
        ./tests/e2e/setup/install_claude_mock.sh
        
    - name: Run E2E tests
      run: |
        cargo test --test e2e_tests -- --test-threads=1
```

## Mock Implementations for External Dependencies
**E2E Claude Mock:**
```rust
// tests/e2e/mocks/claude_e2e_mock.rs
pub struct E2EClaudeMock {
    response_templates: HashMap<String, String>,
    failure_rate: Arc<AtomicU32>,
    response_delay: Duration,
    session_state: Mutex<HashMap<String, SessionState>>,
}

impl E2EClaudeMock {
    pub fn new() -> Self {
        let mut response_templates = HashMap::new();
        
        // Load realistic response templates
        response_templates.insert(
            "simple_analysis".to_string(),
            include_str\!("../fixtures/responses/simple_analysis.json").to_string()
        );
        response_templates.insert(
            "code_review".to_string(),
            include_str\!("../fixtures/responses/code_review.json").to_string()
        );
        
        Self {
            response_templates,
            failure_rate: Arc::new(AtomicU32::new(0)),
            response_delay: Duration::from_millis(500),
            session_state: Mutex::new(HashMap::new()),
        }
    }
    
    pub async fn handle_request(&self, request: ClaudeRequest) -> ClaudeResponse {
        // Simulate processing delay
        tokio::time::sleep(self.response_delay).await;
        
        // Check for simulated failures
        let failure_rate = self.failure_rate.load(Ordering::Relaxed) as f32 / 100.0;
        if rand::random::<f32>() < failure_rate {
            return ClaudeResponse::error("Simulated Claude failure");
        }
        
        // Generate appropriate response based on prompt
        let response_key = self.classify_prompt(&request.prompt);
        let template = self.response_templates.get(&response_key)
            .unwrap_or(&self.response_templates["simple_analysis"]);
        
        ClaudeResponse::success(
            template.clone(),
            request.session_id.unwrap_or_else(|| generate_session_id()),
        )
    }
}
```

## Automation Requirements
**Automated E2E Testing:**
- Run E2E tests on every PR and main branch push
- Scheduled daily runs with extended test suites
- Cross-platform testing on Linux, macOS, and Windows
- Performance regression detection
- Automatic retry on flaky test failures

**Test Environment Management:**
```bash
# tests/e2e/scripts/setup_environment.sh
#\!/bin/bash

setup_e2e_environment() {
    echo "Setting up E2E test environment..."
    
    # Create test data directories
    mkdir -p tests/e2e/{results,logs,tmp}
    
    # Install Claude CLI mock
    install_claude_mock
    
    # Setup test Git repositories
    setup_test_repositories
    
    # Configure test environment variables
    export PARCL_TEST_MODE=1
    export PARCL_LOG_LEVEL=debug
    export CLAUDE_API_KEY=test-key
    
    echo "E2E environment setup complete"
}

cleanup_e2e_environment() {
    echo "Cleaning up E2E test environment..."
    
    # Remove temporary files
    rm -rf tests/e2e/tmp/*
    
    # Kill any running processes
    pkill -f "parcl.*test" || true
    pkill -f "claude.*mock" || true
    
    echo "E2E environment cleanup complete"
}
```

## Implementation Tasks
- [ ] Set up E2E test infrastructure and directory structure
- [ ] Implement test environment management utilities
- [ ] Create comprehensive test repository fixtures
- [ ] Implement core workflow E2E tests
- [ ] Create cross-platform compatibility tests
- [ ] Implement performance and scalability E2E tests
- [ ] Set up error handling and recovery tests
- [ ] Create realistic mock implementations
- [ ] Integrate with CI/CD pipeline
- [ ] Set up monitoring and alerting for E2E test failures

## Success Criteria
- ✅ All major user workflows covered by E2E tests
- ✅ Cross-platform compatibility validated
- ✅ Performance targets met in realistic scenarios
- ✅ Error handling and recovery properly tested
- ✅ E2E tests run reliably in CI environment
- ✅ Clear failure diagnosis and debugging capabilities

## Dependencies
- Mock Claude CLI implementation
- Test repository fixtures and data
- Cross-platform CI/CD environments
- Performance monitoring and analysis tools
- Test environment management scripts

**Priority:** High
**Estimated Effort:** 3-4 weeks
**Labels:** testing, e2e, workflow, integration, cross-platform
