### ISSUE TITLE
Configuration Hierarchy System: Implement project → user → system precedence

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/parcl#3]
## Summary
Implement a robust configuration hierarchy system that loads configuration from multiple sources with proper precedence: project → user → system. This should provide a Viper-like experience for Rust.

### Configuration Precedence (Highest to Lowest)
1. **Project level**: `.parcl/config.yaml` (checked into git, shared across team)
2. **User level**: `~/.config/parcl/config.yaml` (user-specific settings)
3. **System level**: `/etc/parcl/config.yaml` (system-wide defaults)

### Configuration Merging
- Deep merge configuration objects rather than replacing entire sections
- Environment variables should override any file-based configuration
- Command-line flags should have highest precedence
- Support for XDG Base Directory specification on Unix systems

### Discovery and Loading
- Automatically discover and load all available configuration files
- Gracefully handle missing configuration files
- Validate configuration at startup with clear error messages
- Support for configuration reloading without restart

### Configuration Structure
The system should support the full configuration schema as defined in the example config:

```yaml
# Global settings
verbose: false
log_level: info
workspace: ""

# Execution settings  
execution:
  default_jobs: 3
  max_jobs: 10
  timeout: 1h

# Git settings
git:
  default_branch: main
  auth:
    ssh_key_path: ~/.ssh/id_rsa
    username: ""
    token: ""
  worktree:
    base_dir: .parcl/worktrees
    name_pattern: "parcl-{branch}-{timestamp}"
    cleanup_after: 168h

# Claude Code settings
claude:
  binary_path: claude
  default_args: []
  max_turns: 10
  output_format: text
  mcp_servers: {}

# Terminal settings
terminal:
  preferred: auto
  emulators: {}

# Evaluation settings
evaluation:
  enabled: false
  script: scripts/eval.sh
  script_args: []
  script_timeout: 5m
```

### Rust Implementation
- Use `serde` for serialization/deserialization
- Use `serde_yaml` for YAML parsing
- Implement custom merge logic for deep configuration merging
- Use `directories` crate for cross-platform config directory discovery
- Provide builder pattern for configuration construction

### Error Handling
- Clear error messages for YAML syntax errors with line numbers
- Validation errors with specific field names and expected values
- Graceful degradation when config files are unreadable
- Warnings for unknown configuration keys

### CLI Integration
- Configuration should be available through a global `Config` struct
- Support `--config` flag to override default config file locations
- Support `--verbose` and other CLI flags that override config file settings

### Environment Variable Support
- Support `PARCL_CONFIG_PATH` for custom config file location
- Support environment variable overrides with `PARCL_` prefix
- Nested configuration via environment variables (e.g., `PARCL_GIT_WORKTREE_BASE_DIR`)

### Validation and Defaults
- Comprehensive validation of all configuration values
- Smart defaults that work out-of-the-box
- Configuration validation at application startup
- Helpful error messages for invalid configurations

## Implementation Plan

1. **Phase 1**: Extend current config module with hierarchical loading
2. **Phase 2**: Implement deep merging and environment variable support  
3. **Phase 3**: Add comprehensive validation and error handling
4. **Phase 4**: Integration with CLI and testing

## Acceptance Criteria
- [ ] Configuration loads from all three levels (project, user, system)
- [ ] Higher precedence configurations override lower precedence
- [ ] Deep merging works correctly for nested structures
- [ ] Environment variables override file-based configuration
- [ ] Clear error messages for invalid configurations
- [ ] All existing functionality continues to work
- [ ] Comprehensive test coverage
- [ ] Documentation with examples

## Related Issues
- Environment Variable Overrides (#TBD)
- Configuration Validation and Defaults (#TBD)  
- Configuration File Discovery (#TBD)
- YAML Parsing with Viper-like functionality (#TBD)
