### ISSUE TITLE
Implement configuration validation and defaults

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/parcl#41]
## Description
Implement configuration validation and default values system as specified in line 37 of `specs/v1.md`, following the principle of locality of behavior.

## Background
Parcl needs robust configuration validation to ensure all settings are valid before execution. The system should provide sensible defaults while validating user-provided configurations against expected schemas.

## Acceptance Criteria
- [ ] Create `internal/config/schema.go` with configuration struct definitions
- [ ] Implement validation logic for all configuration fields
- [ ] Define and apply sensible defaults for all settings
- [ ] Validate data types, ranges, and required fields
- [ ] Support custom validation rules (e.g., valid Git branch names)
- [ ] Provide clear, actionable error messages for validation failures
- [ ] Add comprehensive unit tests for validation logic
- [ ] Document all configuration options and their defaults

### Configuration Schema
```go
type Config struct {
    Git        GitConfig        `mapstructure:"git" validate:"required"`
    Claude     ClaudeConfig     `mapstructure:"claude" validate:"required"`
    Prompt     PromptConfig     `mapstructure:"prompt"`
    Runner     RunnerConfig     `mapstructure:"runner"`
    Evaluation EvaluationConfig `mapstructure:"evaluation"`
}

type GitConfig struct {
    DefaultBranch      string `mapstructure:"default_branch" default:"main" validate:"required,git_branch"`
    WorktreePrefix     string `mapstructure:"worktree_prefix" default:"parcl-" validate:"required"`
    BareRepoPath       string `mapstructure:"bare_repo_path" default:".parcl/repo" validate:"required,dir_path"`
    WorktreeBasePath   string `mapstructure:"worktree_base_path" default:".parcl/worktrees" validate:"required,dir_path"`
    AutoCleanup        bool   `mapstructure:"auto_cleanup" default:"true"`
}
```

### Validation Functions
- `ValidateConfig(cfg *Config) error` - Main validation entry point
- `SetDefaults(cfg *Config)` - Apply default values
- Custom validators:
  - `ValidateGitBranch(branch string) error`
  - `ValidateAPIKey(key string) error`
  - `ValidateModel(model string) error`
  - `ValidatePath(path string) error`

### Default Values
```yaml
# Built-in defaults
git:
  default_branch: main
  worktree_prefix: parcl-
  bare_repo_path: .parcl/repo
  worktree_base_path: .parcl/worktrees
  auto_cleanup: true

claude:
  model: claude-3-5-sonnet-20241022
  max_requests: 5
  concurrency: 5
  temperature: 0
  timeout: 300

runner:
  parallel_limit: 5
  output_format: json
  progress_display: spinner
  continue_on_error: false
  capture_output: true
```

### Error Messages
- "git.default_branch: invalid branch name 'main/feature', branch names cannot contain '/'"
- "claude.api_key: required field is missing, set ANTHROPIC_API_KEY or provide in config"
- "runner.parallel_limit: must be between 1 and 50, got 100"

## References
- Line 37 of `specs/v1.md`: "Configuration validation and defaults (locality of behavior)"
- Configuration structure in CLAUDE.md
- Viper validation: https://github.com/spf13/viper#unmarshaling
- go-playground/validator: https://github.com/go-playground/validator
