### ISSUE TITLE
YAML Configuration Parsing with Viper-like Functionality

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/parcl#7]
## Summary
Implement robust YAML configuration parsing with Viper-like functionality including advanced features like configuration watching, automatic type conversion, and flexible key access patterns.

### YAML Parsing Features
- Support for all YAML 1.2 features including:
  - Multi-document YAML files
  - Complex nested structures
  - Arrays and maps
  - Type coercion (strings to numbers, durations, etc.)
  - Comments and documentation preservation
- Graceful handling of malformed YAML with precise error reporting
- Support for YAML anchors and references for configuration reuse

### Viper-like Functionality
- Flexible key access with dot notation (e.g., `config.get("git.worktree.base_dir")`)
- Automatic type conversion and casting
- Key case-insensitivity options
- Support for configuration aliasing (alternative key names)
- Configuration validation with custom validators

### Advanced Features
- Configuration file watching and hot-reload capabilities
- Macro expansion and templating within configuration files
- Configuration schema validation with JSON Schema
- Export configuration to different formats (JSON, TOML, etc.)

### YAML Schema Support
The parser should handle the complete configuration schema:

```yaml
# Global configuration with environment variable substitution
verbose: ${PARCL_VERBOSE:-false}
log_level: ${PARCL_LOG_LEVEL:-info}
workspace: ${PARCL_WORKSPACE:-""}

# Execution settings with validation
execution:
  default_jobs: 3  # Must be > 0
  max_jobs: 10     # Must be >= default_jobs
  timeout: 1h      # Duration parsing (s, m, h, d)

# Git configuration with complex nesting
git:
  default_branch: main
  auth:
    ssh_key_path: ~/.ssh/id_rsa  # Path expansion
    username: ${GIT_USERNAME:-""}
    token: ${GIT_TOKEN:-""}
  worktree:
    base_dir: .parcl/worktrees
    name_pattern: "parcl-{branch}-{timestamp}"  # Template strings
    cleanup_after: 168h  # Duration with validation

# Claude Code with dynamic server configuration
claude:
  binary_path: claude
  default_args: []
  max_turns: 10
  output_format: text  # Enum validation: text|json|stream-json
  mcp_servers:
    filesystem: &filesystem_server
      command: npx
      args:
        - "-y"
        - "@modelcontextprotocol/server-filesystem"
        - "/path/to/allowed/files"
    github:
      <<: *filesystem_server  # YAML merge key
      args:
        - "-y"
        - "@modelcontextprotocol/server-github"
      env:
        GITHUB_TOKEN: ${GITHUB_TOKEN}

# Terminal configuration with platform detection
terminal:
  preferred: auto  # auto|ghostty|gnome-terminal|kitty|iterm2
  emulators:
    ghostty:
      binary_path: ghostty
      args: ["-e"]
      available_on: [linux, macos]
    gnome-terminal:
      binary_path: gnome-terminal
      args: ["--"]
      available_on: [linux]
    iterm2:
      binary_path: open
      args: ["-a", "iTerm"]
      available_on: [macos]
    kitty:
      binary_path: kitty
      args: []
      available_on: [linux, macos, windows]

# Evaluation with script validation
evaluation:
  enabled: false
  script: scripts/eval.sh  # File existence validation
  script_args:
    - "${worktree}"    # Template variable
    - "${model}"
  script_timeout: 5m
```

#### Core Traits and Structures
```rust
pub trait ConfigParser {
    fn parse_yaml(&self, content: &str) -> Result<ConfigValue>;
    fn validate_schema(&self, config: &ConfigValue) -> Result<()>;
    fn merge_configs(&self, base: ConfigValue, override: ConfigValue) -> ConfigValue;
}

pub trait ConfigAccessor {
    fn get<T: DeserializeOwned>(&self, key: &str) -> Option<T>;
    fn get_string(&self, key: &str) -> Option<String>;
    fn get_duration(&self, key: &str) -> Option<Duration>;
    fn get_path(&self, key: &str) -> Option<PathBuf>;
    fn is_set(&self, key: &str) -> bool;
}

pub struct ConfigManager {
    values: ConfigValue,
    schema: Option<JsonSchema>,
    watchers: HashMap<PathBuf, FileWatcher>,
}
```

#### Type Conversion Support
- Automatic string to numeric conversion
- Duration parsing from strings (e.g., "1h30m", "300s")
- Path expansion for `~` and environment variables
- Boolean parsing from various formats ("true", "yes", "1", etc.)
- Array and object parsing from various input formats

#### Error Handling
```rust
#[derive(Debug, Error)]
pub enum ConfigError {
    #[error("YAML syntax error at line {line}, column {column}: {message}")]
    YamlSyntax { line: usize, column: usize, message: String },
    
    #[error("Configuration validation failed for key '{key}': {reason}")]
    ValidationFailed { key: String, reason: String },
    
    #[error("Type conversion failed for key '{key}': expected {expected}, got {actual}")]
    TypeConversion { key: String, expected: String, actual: String },
    
    #[error("Required configuration key '{key}' is missing")]
    MissingRequired { key: String },
    
    #[error("Unknown configuration key '{key}' in section '{section}'")]
    UnknownKey { key: String, section: String },
}
```

#### Environment Variable Substitution
- Support `${VAR}` syntax for environment variable substitution
- Support `${VAR:-default}` syntax for default values
- Recursive variable substitution
- Validation of required environment variables

#### Configuration Templates
- Template variable support in configuration values
- Built-in template functions (e.g., `${timestamp}`, `${hostname}`)
- Custom template function registration

#### File Watching
- Monitor configuration files for changes
- Automatic reload with validation
- Callback system for configuration change notifications
- Debouncing for rapid file changes

### Dependencies
```toml
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
jsonschema = "0.17"
notify = "6.0"          # File watching
duration-str = "0.7"    # Duration parsing
shellexpand = "3.1"     # Path expansion
tera = "1.19"          # Template engine
thiserror = "1.0"
anyhow = "1.0"
```

### CLI Integration
- Support for `--config-validate` flag to validate configuration without running
- Support for `--config-export <format>` to export configuration
- Configuration diff tool to show effective configuration from multiple sources

### Performance Requirements
- Configuration parsing should complete in < 100ms for typical config files
- Memory usage should be minimal and proportional to config size
- File watching should have minimal CPU overhead

### Unit Tests
- Test all YAML parsing edge cases
- Test environment variable substitution
- Test template expansion
- Test configuration merging logic
- Test validation with various invalid configurations

### Integration Tests  
- Test configuration loading from multiple sources
- Test file watching and reload functionality
- Test CLI integration
- Test error reporting and user experience

### Property-Based Tests
- Fuzz testing with randomly generated YAML
- Property testing for configuration merging associativity
- Roundtrip testing (parse → serialize → parse)

## Performance Benchmarks
- Benchmark configuration loading time
- Benchmark memory usage with large configurations
- Benchmark file watching overhead

## Acceptance Criteria
- [ ] Parse complex YAML configurations without errors
- [ ] Support all required type conversions
- [ ] Environment variable substitution works correctly
- [ ] Configuration validation provides clear error messages
- [ ] File watching and hot-reload functionality works
- [ ] Template expansion works for all use cases
- [ ] Performance meets requirements (< 100ms parsing)
- [ ] Comprehensive test coverage (> 90%)
- [ ] Integration with existing codebase without breaking changes

## Related Issues
- Configuration Hierarchy System (#3)
- Environment Variable Overrides (#TBD)
- Configuration Validation and Defaults (#TBD)
