### ISSUE TITLE
Add CI/CD support for NixOS VM tests in GitHub Actions

### ISSUE THREAD

**Issue by conneroisu** [conneroisu/parcl#73]
## Description

Implement GitHub Actions workflows that run NixOS VM tests in CI/CD pipelines. This enables automated testing of Parcl in realistic environments with every commit and pull request.

## Background

Running NixOS VM tests in CI requires:
- KVM support in GitHub Actions runners
- Efficient caching of Nix dependencies
- Proper test result reporting and artifacts
- Integration with existing CI workflows
- Performance optimization to keep CI times reasonable

### 1. GitHub Actions Workflow
```yaml
# .github/workflows/nixos-tests.yml
name: NixOS Integration Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly full test run

jobs:
  nixos-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-suite:
          - framework
          - parallel-worktree
          - terminal-emulation
          - integration-scenarios
          - performance
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            system-features = nixos-test benchmark big-parallel kvm
            substituters = https://cache.nixos.org https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
      
      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: parcl
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          sudo chmod 666 /dev/kvm
      
      - name: Run NixOS Tests
        run: |
          nix flake check --print-build-logs --keep-going .#checks.x86_64-linux.${{ matrix.test-suite }}
        timeout-minutes: 30
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.test-suite }}
          path: |
            result/test-results.xml
            result/screenshots/
            result/logs/
```

### 2. Test Result Collection Script
```nix
# tests/nixos/lib/test-driver.nix
{ writeShellScriptBin, python3Packages }:

writeShellScriptBin "collect-test-results" ''
  #!/usr/bin/env bash
  set -euo pipefail
  
  OUTPUT_DIR="${1:-./result}"
  mkdir -p "$OUTPUT_DIR"/{logs,screenshots,reports}
  
  # Convert Python test output to JUnit XML
  python3 -m pytest_jsonreport.plugin \
    --json-report-file="$OUTPUT_DIR/test-results.json" \
    "$TEST_SCRIPT"
  
  # Convert to JUnit for GitHub Actions
  python3 -c "
  import json
  import xml.etree.ElementTree as ET
  
  with open('$OUTPUT_DIR/test-results.json') as f:
      data = json.load(f)
  
  # Generate JUnit XML...
  "
  
  # Collect VM screenshots if any
  find /tmp -name "*.png" -type f -exec cp {} "$OUTPUT_DIR/screenshots/" \;
  
  # Collect logs
  journalctl --no-pager > "$OUTPUT_DIR/logs/system.log" || true
  dmesg > "$OUTPUT_DIR/logs/kernel.log" || true
''
```

#### Nix Build Caching
```yaml
- name: Configure Nix Cache
  run: |
    # Use GitHub Actions cache for Nix store
    echo "post-build-hook = $PWD/.github/scripts/upload-to-cache.sh" >> ~/.config/nix/nix.conf
    
    # Enable parallel builds
    echo "max-jobs = auto" >> ~/.config/nix/nix.conf
    echo "cores = 0" >> ~/.config/nix/nix.conf

- name: Cache Nix Store
  uses: actions/cache@v3
  with:
    path: |
      ~/.local/share/nix/root
      ~/.cache/nix
    key: ${{ runner.os }}-nix-${{ hashFiles('flake.lock') }}
    restore-keys: |
      ${{ runner.os }}-nix-
```

#### Test Parallelization
```nix
# tests/nixos/parallel-runner.nix
{ pkgs, lib, ... }:

{
  # Split tests into parallel jobs
  parallelTests = lib.splitList 4 allTests;
  
  # Run test groups in parallel
  runParallelTests = pkgs.writeShellScript "run-parallel-tests" ''
    parallel -j 4 --halt now,fail=1 \
      'nix build .#checks.x86_64-linux.{}' \
      ::: ${parallelTests[@]}
  '';
}
```

#### GitHub Actions Summary
```yaml
- name: Generate Test Summary
  if: always()
  run: |
    cat >> $GITHUB_STEP_SUMMARY <<EOF
    ## NixOS Test Results
    
    ### Test Suite: ${{ matrix.test-suite }}
    
    | Test | Status | Duration |
    |------|--------|----------|
    EOF
    
    # Parse test results and add to summary
    python3 .github/scripts/parse-test-results.py \
      --input result/test-results.xml \
      --format markdown >> $GITHUB_STEP_SUMMARY

- name: Comment PR with Results
  if: github.event_name == 'pull_request'
  uses: actions/github-script@v7
  with:
    script: |
      const results = require('./result/test-results.json');
      const comment = `
      ## 🧪 NixOS Test Results
      
      **Suite**: ${{ matrix.test-suite }}
      **Status**: ${results.status}
      **Duration**: ${results.duration}s
      
      <details>
      <summary>Detailed Results</summary>
      
      \`\`\`
      ${results.details}
      \`\`\`
      </details>
      `;
      
      github.rest.issues.createComment({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        body: comment
      });
```

#### Conditional Test Execution
```yaml
- name: Determine Tests to Run
  id: test-filter
  run: |
    # Only run affected tests based on changed files
    CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.sha }})
    
    if echo "$CHANGED_FILES" | grep -q "internal/terminal"; then
      echo "run-terminal-tests=true" >> $GITHUB_OUTPUT
    fi
    
    if echo "$CHANGED_FILES" | grep -q "internal/git"; then
      echo "run-worktree-tests=true" >> $GITHUB_OUTPUT
    fi

- name: Run Terminal Tests
  if: steps.test-filter.outputs.run-terminal-tests == 'true'
  run: nix flake check .#checks.x86_64-linux.terminal-emulation
```

#### SSH Debug Access
```yaml
- name: Setup tmate session
  if: ${{ failure() && github.event_name == 'workflow_dispatch' }}
  uses: mxschmitt/action-tmate@v3
  with:
    limit-access-to-actor: true
    timeout-minutes: 30

- name: Upload Debug Artifacts
  if: failure()
  uses: actions/upload-artifact@v4
  with:
    name: debug-artifacts-${{ matrix.test-suite }}
    path: |
      /tmp/vm-*.log
      /tmp/screenshots/
      core.*
    retention-days: 7
```

## Acceptance Criteria

- [ ] GitHub Actions workflow successfully runs NixOS tests
- [ ] KVM acceleration enabled for reasonable test performance
- [ ] Test results properly reported in GitHub UI
- [ ] Efficient caching reduces subsequent run times
- [ ] Parallel test execution for faster CI
- [ ] PR comments with test summaries
- [ ] Debug artifacts available for failed tests
- [ ] Integration with existing Go tests and linting

### Performance Targets
- Full test suite completes in under 30 minutes
- Individual test suites complete in under 10 minutes
- Cache hit rate > 80% for dependency builds

### Resource Requirements
- GitHub-hosted runners with KVM support
- 8GB RAM minimum for VM tests
- 20GB disk space for Nix store

### Security Considerations
- Cachix auth token stored as secret
- VM tests run in isolated environment
- No sensitive data in test artifacts

## Dependencies
- NixOS VM test implementation (#66-#72)
- GitHub Actions runner with KVM support
- Cachix account for build caching

## References
- [GitHub Actions Virtual Environments](https://github.com/actions/virtual-environments)
- [DeterminateSystems Nix Installer](https://github.com/DeterminateSystems/nix-installer)
- [Example: NixOS tests in CI](https://github.com/NixOS/nixpkgs/blob/master/.github/workflows/tests.yml)
